name: Update From Template and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  update-and-create-pr:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Create new branch for template updates
        run: git checkout -b template-updates

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "EnterpriseNest Template Bot"

      - name: Add template repository as a remote
        run: git remote add template https://github.com/TheGoatedDev/EnterpriseNest.git || true

      - name: Fetch changes from template repository
        run: git fetch template

      - name: Merge changes from template into template-updates
        run: |
          git merge template/main --allow-unrelated-histories -m "Merge template changes" -s recursive -X theirs

      - name: Push template-updates branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: template-updates

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.changes_detected == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base develop --head template-updates --title "Update from template" --body "This PR updates the template from the latest changes in the template repository."